SBL: Revert C++ Build Fix in SBL invalid defines
- Following params in sblSlaveCoreInfo_t structure are of type int32_t
  - proc_id, dev_id, clk_id, clk_freq
- In sbl_soc_cfg.h, these params  #define for invalid cores are defined
  as 0xBAD00000 (which is 64bit)
  - This results in C++ build failure
    ```
    error: constant expression evaluates to 3134193664 which cannot be narrowed to type 'int32_t' (aka 'int') [-Wc++11-narrowing]
    ```
  - Fix was to update the #define to 32 bit 0xBAD0
- But SBL in many places uses the hardcoding 0xBAD00000 to check for invalids
  - This resulted in SBL failures for invalid cores
    - Sciclient_procBootRequestProcessor was inoked for invalid cores
- Hence revert the fix to update defines from 0xBAD00000 -> 0xBAD0
- Currently C++ build suppress this warning using ```-Wno-c++11-narrowing```
  - To avoid the narrowing issues, SBL lib needs to be fixed properly to avoid use hardcoding in many places
    and use an appropriate invaid macro(which can be used everywhere)

Signed-off-by: Don Dominic <a0486429@ti.com>