am62: linker: r5_btcm: Increase DDR region
With latest changes the default size set for DDR is not enough, increase it
to fix the linker issue.

```
   program will not fit into available memory, or the section contains a call
   site that requires a trampoline that can't be generated for this section.
   run placement with alignment fails for section ".data" size 0x1052c8.
   Available memory ranges:
   DDR          size: 0xfffff      unused: 0xd2493      max hole: 0xd2440
error: errors encountered during linking;
```

Signed-off-by: Vishal Mahaveer <vishalm@ti.com>